.PHONY: clean All

All:
	@echo "----------Building project:[ VectorReverse - Debug ]----------"
	@cd "ArrayReverse" && "$(MAKE)" -f  "VectorReverse.mk"
clean:
	@echo "----------Cleaning project:[ VectorReverse - Debug ]----------"
	@cd "ArrayReverse" && "$(MAKE)" -f  "VectorReverse.mk" clean
